=== naco-catacomb/idea-plugin-xstructure/src/main/resources/org/sylfra/idea/plugins/xstructure/resources/schemas/xstructure_1_1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xs="http://plugins.intellij.net/xstructure"
            targetNamespace="http://plugins.intellij.net/xstructure"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified"
            version="1.1">

  <xsd:element name="xstructure">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:supported-schemas"/>
        <xsd:element ref="xs:mappings"/>
      </xsd:sequence>
      <xsd:attribute name="version" type="xsd:string" use="required"/>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="implType" type="xs:implType" use="required"/>
      <xsd:attribute name="priority" type="xsd:int" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="supported-schemas">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:schema" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="schema">
    <xsd:complexType>
      <xsd:attribute name="uri" type="xsd:anyURI" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="mappings">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="xs:mapping" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="defaultSkip" type="xs:skipMode" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="mapping">
    <xsd:complexType>
      <xsd:attribute name="match" type="xsd:string" use="required"/>
      <xsd:attribute name="label" type="xsd:string" use="optional"/>
      <xsd:attribute name="skip" type="xs:skipMode" use="optional"/>
      <xsd:attribute name="tip" type="xsd:string" use="optional"/>
      <xsd:attribute name="icon" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="implType">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="default"/>
      <xsd:enumeration value="xpath"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="skipMode">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="none"/>
      <xsd:enumeration value="this"/>
      <xsd:enumeration value="children"/>
      <xsd:enumeration value="all"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/default-mappings/default/docbook_book_5_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Docbook module, versions 5.0 -->
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="default" name="DocBook/Book" version="1.4" priority="10">
    <supported-schemas>
        <schema uri="http://www.docbook.org/xml/5.0/xsd/docbook.xsd"/>
        <schema uri="http://www.docbook.org/xml/5.0/dtd/docbook.dtd"/>
    </supported-schemas>

    <mappings>
        <mapping match=".*/book|.*/article" label="{title} | {subtitle}" icon="/nodes/ppLib.png"/>
        <mapping match=".*/title" skip="all"/>
        <mapping match=".*/subtitle" skip="all"/>
        <mapping match=".*/info" skip="children" icon="/ant/message.png"/>
        <mapping match=".*/toc" skip="children" icon="/nodes/DataTables.png"/>

        <mapping match=".*/chapter" label="{title}" icon="/nodes/folder.png"/>
        <mapping match=".*/appendix" label="{title}" icon="/modules/sourceClosed.png"/>

        <mapping match=".*/sect\d+" label="{title}" icon="/nodes/copyOfFolder.png"/>
        <mapping match=".*/section" label="{title}" icon="/nodes/folder.png"/>
        <mapping match=".*/sectioninfo" label="Author: {author}, Date: {date}"/>

        <mapping match=".*/formalpara" label="{title}"/>
        <mapping match=".*/example" label="{title}"/>
        <mapping match=".*/programlisting" label="Language: {@language}" icon="/debugger/threadSuspended.png"/>

        <mapping match=".*/para" skip="all"/>

        <mapping match=".*/emphasis" skip="all"/>

        <mapping match=".*/table" label="{caption}" skip="children" icon="/nodes/DataTables.png"/>

        <mapping match=".*/qandaentry" label="{question/para}" skip="children" icon="/general/todoQuestion.png"/>
        <mapping match=".*/qandaset" label="Q&amp;A SET" icon="/general/todoQuestion.png"/>

        <!--Inline elements whith short content-->
        <mapping match=".*/code|.*/titleabbrev" label="{.}"/>
    </mappings>
</xstructure>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/default-mappings/default/spring_beans_2.x.xml
<?xml version="1.0" encoding="UTF-8"?>
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="default" name="Spring Beans 2.x" version="1.0" priority="9">
  <supported-schemas>
    <schema uri="http://www.springframework.org/schema/beans/spring-beans-2.\d.xsd"/>
  </supported-schemas>
  <mappings>
    <mapping match="/beans" tip="{description}" icon="/javaee/ejbModule.png"/>
    <mapping match="/beans/description" skip="all"/>
    <mapping match="/beans/import" label="{@resource}" icon="/actions/export.png"/>
    <mapping match="/beans/bean" label="{@id}" tip="{description}" icon="/objectBrowser/bean.png"/>
    <mapping match="/beans/bean/description" skip="all"/>
    <mapping match="/beans/bean/constructor-arg" icon="/nodes/ejbCreateMethod.png"/>
    <mapping match="/.*/property" label="{@name}" icon="/nodes/parameter.png"/>
    <mapping match="/.*/property/(list|props|map)" skip="this"/>
    <mapping match="/.*/(property/list|constructor-arg)/value" label="{.}" icon="/nodes/parameter.png"/>
    <mapping match="/.*/property/props/prop" label="{@key}={.}" icon="/nodes/property.png"/>
    <mapping match="/.*/property/map/entry" label="{@key}={value}" skip="children" icon="/nodes/property.png"/>
  </mappings>
</xstructure>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/docs/wiki/files/mpd_jbossportal_portlet_instances_2_6_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="default" name="jboss-portal-instances" version="1.2" priority="10">
  <supported-schemas>
    <schema uri="http://www.jboss.org/portal/dtd/portlet-instances_2_6.dtd"/>
  </supported-schemas>
  <mappings>
    <mapping match="/deployments/deployment" skip="children" label="{instance/instance-id}" icon="/nodes/deploy.png"/>
    <mapping match="/deployments/deployment/instance" skip="this"/>
    <mapping match="/deployments/deployment/instance/(instance-id|portlet-ref)" skip="this"/>
    <mapping match="/deployments/deployment/instance/preferences" skip="this"/>
    <mapping match="/deployments/deployment/instance/preferences/preference" label="{name}" skip="children" icon="/nodes/parameter.png"/>
  </mappings>
</xstructure>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/default-mappings/default/maven_4_0_simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="default" name="Maven POM / simple" version="1.0" priority="10">
  <supported-schemas>
    <schema uri="http://maven.apache.org/maven-v4_0_0.xsd"/>
  </supported-schemas>
  <mappings defaultSkip="all">
    <mapping match="/project" label="{name} - v{version}" tip="{description}"/>
    <mapping match="/project/developers"/>
    <mapping match="/project/developers/developer" label="{name}" icon="/fileTypes/custom.png"/>
    <mapping match="/project/dependencies" icon="/nodes/moduleGroupClosed.png"/>
    <mapping match="/project/build"/>
    <mapping match="/project/build/plugins" icon="/nodes/moduleGroupClosed.png"/>
    <mapping match="/project/build/plugins/plugin" label="{groupId}:{artifactId}" icon="/nodes/plugin.png"/>
    <mapping match="/project/dependencies/dependency" label="{groupId}:{artifactId}" icon="/objectBrowser/showLibraryContents.png"/>
    <mapping match="/project/(repositories|pluginRepositories)" icon="/nodes/moduleGroupClosed.png"/>
    <mapping match="/project/(repositories|pluginRepositories)/(repository|pluginRepository)" label="{id}" icon="/nodes/pluginnotinstalled.png"/>
    <mapping match="/project/profiles" icon="/nodes/moduleGroupClosed.png"/>
    <mapping match="/project/profiles/profile" label="{id}" icon="/actions/properties.png"/>
  </mappings>
</xstructure>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/default-mappings/default/maven_4_0_rich.xml
<?xml version="1.0" encoding="UTF-8"?>
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="default" name="Maven POM / rich" version="1.0" priority="20">
  <supported-schemas>
    <schema uri="http://maven.apache.org/maven-v4_0_0.xsd"/>
  </supported-schemas>
  <mappings>
    <mapping match="/project" label="{name} [{groupId}:{artifactId}] - v{version}"
             tip="{description}"/>
    <mapping match="/project/(modelVersion|groupId|artifactId|name|description|version)"
             skip="all"/>
    <mapping match="/project/packaging" label="{.}"/>
    <mapping match="/project/inceptionYear" label="{.}"/>
    <mapping match="/project/(ciManagement|issueManagement)" label="{system}" skip="children"/>
    <mapping match="/project/modules/module" label="{.}" icon="/nodes/ModuleClosed.png"/>
    <mapping match="/project/licenses" label="{license/name}" skip="children"/>
    <mapping match="/project/build/extensions/extension" label="{groupId}:{artifactId}"
             skip="children"/>
    <mapping match="/project/developers/developer" label="{name}" skip="children" icon="/fileTypes/custom.png"/>
    <mapping match="/project/profiles/profile" label="{id}" skip="children" icon="/actions/properties.png"/>
    <mapping match="/project/pluginRepositories/pluginRepository" icon="/nodes/pluginnotinstalled.png"/>
    <mapping match="/project/(/build/plugins|pluginRepositories|repositories)" icon="/nodes/moduleGroupClosed.png"/>
    <mapping match="/.*/plugin" label="{groupId}:{artifactId}" skip="children" icon="/nodes/plugin.png"/>
    <mapping match="/.*/dependency" label="{groupId}:{artifactId}" skip="children" icon="/objectBrowser/showLibraryContents.png"/>
    <mapping match="/.*/.*epository" label="{id}" skip="children"/>
  </mappings>
</xstructure>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/default-mappings/default/docbook_website_2_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Docbook website module, versions 2.5 and 2.6 -->
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="default" name="DocBook/Website" version="1.0" priority="10">
  <supported-schemas>
    <schema uri="-//Norman Walsh//DTD Website ( Full)?V2.(5|6).*//EN"/>
    <schema uri="-//OASIS//DTD DocBook XML V4.5//EN"/>
  </supported-schemas>

  <mappings>
    <mapping match="/webpage" label="{@id}"/>
    <mapping match="/webpage/config" skip="all"/>
    <mapping match="/webpage/head" skip="children" label="{title}"/>

    <mapping match=".*/sect\d+" label="{title}"/>
    <mapping match=".*/section" label="{title}"/>
    <mapping match=".*/sectioninfo" label="Author: {author}, Date: {date}"/>

    <mapping match=".*/formalpara" label="{title}"/>
    <mapping match=".*/example" label="{title}"/>
    <mapping match=".*/programlisting" label="Language: {@lang}"/>

    <mapping match=".*/para" label="{.}" tip="{.}" maxlength="45"/>
    <mapping match=".*/title" skip="all"/>

    <!--Inline elements whith short content-->
    <mapping match=".*/code|.*/emphasis|.*/titleabbrev" label="{.}"/>
  </mappings>
</xstructure>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/other-mappings/web-app_2_4-xpath.xml
<?xml version="1.0" encoding="UTF-8"?>
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="xpath" name="webapp" version="1.1" priority="20">
  <supported-schemas>
    <schema uri="http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"/>
  </supported-schemas>
  <mappings>
    <mapping match="/web-app" label="@version"/>
    <mapping match="/web-app/(context-param|filter|servlet)/init-param"
             label="./*[name()='param-name']/text()"/>
    <mapping match="/web-app/context-parama/*" skip="all"/>
    <mapping match="/web-app/(servlet|servlet-mapping)" label="./*[name()='servlet-name']/text()"
             tip="aaa"/>
    <mapping match="/web-app/(context-param|filter|servlet)/init-param/*" skip="all"/>
    <mapping match="/web-app/(servlet|servlet-mapping)/*" skip="all"/>
  </mappings>
</xstructure>

=== naco-catacomb/idea-plugin-xstructure/src/main/config/default-mappings/default/web_app_2_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<xstructure xmlns="http://plugins.intellij.net/xstructure"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://plugins.intellij.net/xstructure http://plugins.intellij.net/xstructure/ns/xstructure_1_1.xsd"
            implType="default" name="webapp" version="1.0" priority="10">
  <supported-schemas>
    <schema uri="http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"/>
  </supported-schemas>
  <mappings>
    <mapping match="/web-app" label="{display-name}" tip="{description}" icon="/javaee/webModule.png"/>
    <mapping match="/web-app/(display-name|description)" skip="all"/>
    <mapping match="/web-app/listener" label="{listener-class}" skip="children" icon="/nodes/weblistener.png"/>
    <mapping match="/web-app/context-param" label="{param-name}={param-value}" skip="children" icon="/nodes/parameter.png"/>
    <mapping match="/web-app/filter" label="{filter-name}" skip="children" icon="/ant/filter.png"/>
    <mapping match="/web-app/error-page" label="{error-code}{exception-type}" skip="children" icon="/runConfigurations/testError.png"/>
    <mapping match="/web-app/servlet" label="{servlet-name}" skip="children" tip="{description}" icon="/nodes/servlet.png"/>
    <mapping match="/web-app/servlet-mapping" label="{servlet-name}" skip="children" tip="{description}" icon="/nodes/servletMapping.png"/>
    <mapping match="/web-app/(filter|servlet)/init-param" label="{param-name}={param-value}" skip="children" icon="/nodes/parameter.png"/>
    <mapping match="/web-app/jsp-config/taglib" label="{taglib-uri}" skip="children" icon="/nodes/ppJar.png"/>
  </mappings>
</xstructure>
